version: "3.4"

services:

  shorty-postgres-server:
    container_name: shorty-postgres-server
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=shorty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
  
  shorty-redis:
    container_name: shorty-redis
    image: redis:5.0.5-alpine
    expose:
      - 6379
    ports:
      - "6379:6379"